from .level_serializer import LevelSerializer
from .department_serializer import DepartmentSerializer
from .course_serializer import CourseDetailsSerializer
from .topic_serializer import TopicSerializer
from .material_serializer import MaterialSerializer
from .enrollment_serializer import EnrollmentSerializer
