# Generated by Django 6.0.3 on 2026-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performance',
            name='best_score',
            field=models.FloatField(default=0),
        ),
    ]
