# Generated by Django 6.0.3 on 2026-03-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_alter_performance_average_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='level',
        ),
        migrations.AddField(
            model_name='teacher',
            name='level',
            field=models.ManyToManyField(related_name='teachers', to='handler.level'),
        ),
    ]
