# Generated by Django 6.0.3 on 2026-03-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0003_remove_teacher_level_teacher_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='handler.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester')], max_length=30),
        ),
    ]
