# Generated by Django 6.0.3 on 2026-03-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0004_course_teacher_alter_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
